# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Reset all data
Kabupaten.destroy_all
Province.destroy_all
Dt2Category.destroy_all

kabupatens = [
  ["Aceh","Kabupaten","Aceh Barat","Meulaboh"],
  ["Aceh","Kabupaten","Aceh Barat Daya","Blangpidie"],
  ["Aceh","Kabupaten","Aceh Besar","Kota Jantho"],
  ["Aceh","Kabupaten","Aceh Jaya","Calang"],
  ["Aceh","Kabupaten","Aceh Selatan","Tapak Tuan"],
  ["Aceh","Kabupaten","Aceh Singkil","Singkil"],
  ["Aceh","Kabupaten","Aceh Tamiang","Karang Baru"],
  ["Aceh","Kabupaten","Aceh Tengah","Takengon"],
  ["Aceh","Kabupaten","Aceh Tenggara","Kutacane"],
  ["Aceh","Kabupaten","Aceh Timur","Idi Rayeuk"],
  ["Aceh","Kabupaten","Aceh Utara","Lhoksukon"],
  ["Aceh","Kabupaten","Bener Meriah","Simpang Tiga Redelong"],
  ["Aceh","Kabupaten","Bireuen","Bireuen"],
  ["Aceh","Kabupaten","Gayo Lues","Blang Kejeren"],
  ["Aceh","Kabupaten","Nagan Raya","Suka Makmue"],
  ["Aceh","Kabupaten","Pidie","Sigli"],
  ["Aceh","Kabupaten","Pidie Jaya","Meureudu"],
  ["Aceh","Kabupaten","Simeulue","Sinabang"],
  ["Aceh","Kota","Banda Aceh",""],
  ["Aceh","Kota","Langsa",""],
  ["Aceh","Kota","Lhokseumawe",""],
  ["Aceh","Kota","Sabang",""],
  ["Aceh","Kota","Subulussalam",""],
  ["Sumatera Utara","Kabupaten","Asahan","Kisaran"],
  ["Sumatera Utara","Kabupaten","Batubara","Limapuluh"],
  ["Sumatera Utara","Kabupaten","Dairi","Sidikalang"],
  ["Sumatera Utara","Kabupaten","Deli Serdang","Lubuk Pakam"],
  ["Sumatera Utara","Kabupaten","Humbang Hasundutan","Dolok Sanggul"],
  ["Sumatera Utara","Kabupaten","Karo","Kabanjahe"],
  ["Sumatera Utara","Kabupaten","Labuhanbatu","Rantau Prapat"],
  ["Sumatera Utara","Kabupaten","Labuhanbatu Selatan","Kota Pinang"],
  ["Sumatera Utara","Kabupaten","Labuhanbatu Utara","Aek Kanopan"],
  ["Sumatera Utara","Kabupaten","Langkat","Stabat"],
  ["Sumatera Utara","Kabupaten","Mandailing Natal","Panyabungan"],
  ["Sumatera Utara","Kabupaten","Nias","Gunung Sitoli"],
  ["Sumatera Utara","Kabupaten","Nias Barat","Lahomi"],
  ["Sumatera Utara","Kabupaten","Nias Selatan","Teluk Dalam"],
  ["Sumatera Utara","Kabupaten","Nias Utara","Lotu"],
  ["Sumatera Utara","Kabupaten","Padang Lawas","Sibuhuan"],
  ["Sumatera Utara","Kabupaten","Padang Lawas Utara","Gunung Tua"],
  ["Sumatera Utara","Kabupaten","Pakpak Bharat","Salak"],
  ["Sumatera Utara","Kabupaten","Samosir","Pangururan"],
  ["Sumatera Utara","Kabupaten","Serdang Bedagai","Sei Rampah"],
  ["Sumatera Utara","Kabupaten","Simalungun","Raya"],
  ["Sumatera Utara","Kabupaten","Tapanuli Selatan","Sipirok"],
  ["Sumatera Utara","Kabupaten","Tapanuli Tengah","Pandan"],
  ["Sumatera Utara","Kabupaten","Tapanuli Utara","Tarutung"],
  ["Sumatera Utara","Kabupaten","Toba Samosir","Balige"],
  ["Sumatera Utara","Kota","Binjai","Binjai Kota"],
  ["Sumatera Utara","Kota","Gunungsitoli",""],
  ["Sumatera Utara","Kota","Medan",""],
  ["Sumatera Utara","Kota","Padangsidempuan",""],
  ["Sumatera Utara","Kota","Pematangsiantar",""],
  ["Sumatera Utara","Kota","Sibolga",""],
  ["Sumatera Utara","Kota","Tanjungbalai",""],
  ["Sumatera Utara","Kota","Tebing Tinggi",""],
  ["Bengkulu","Kabupaten","Bengkulu Selatan","Kota Manna"],
  ["Bengkulu","Kabupaten","Bengkulu Tengah","Karang Tinggi"],
  ["Bengkulu","Kabupaten","Bengkulu Utara","Arga Makmur"],
  ["Bengkulu","Kabupaten","Kaur","Bintuhan"],
  ["Bengkulu","Kabupaten","Kepahiang","Kepahiang"],
  ["Bengkulu","Kabupaten","Lebong","Muara Aman"],
  ["Bengkulu","Kabupaten","Mukomuko","Mukomuko"],
  ["Bengkulu","Kabupaten","Rejang Lebong","Curup"],
  ["Bengkulu","Kabupaten","Seluma","Tais"],
  ["Bengkulu","Kota","Bengkulu",""],
  ["Jambi","Kabupaten","Batanghari","Muara Bulian"],
  ["Jambi","Kabupaten","Bungo","Muara Bungo"],
  ["Jambi","Kabupaten","Kerinci","Sungaipenuh"],
  ["Jambi","Kabupaten","Merangin","Bangko"],
  ["Jambi","Kabupaten","Muaro Jambi","Sengeti"],
  ["Jambi","Kabupaten","Sarolangun","Sarolangun"],
  ["Jambi","Kabupaten","Tanjung Jabung Barat","Kuala Tungkal"],
  ["Jambi","Kabupaten","Tanjung Jabung Timur","Muara Sabak"],
  ["Jambi","Kabupaten","Tebo","Muara Tebo"],
  ["Jambi","Kota","Jambi","Jambi"],
  ["Jambi","Kota","Sungai Penuh","Sungai Penuh"],
  ["Riau","Kabupaten","Bengkalis","Bengkalis"],
  ["Riau","Kabupaten","Indragiri Hilir","Tembilahan"],
  ["Riau","Kabupaten","Indragiri Hulu","Rengat"],
  ["Riau","Kabupaten","Kampar","Bangkinang"],
  ["Riau","Kabupaten","Kuantan Singingi","Taluk Kuantan"],
  ["Riau","Kabupaten","Pelalawan","Pangkalan Kerinci"],
  ["Riau","Kabupaten","Rokan Hilir","Bagan Siapi-api"],
  ["Riau","Kabupaten","Rokan Hulu","Pasir Pengaraian"],
  ["Riau","Kabupaten","Siak","Siak Sri Indrapura"],
  ["Riau","Kabupaten","Kepulauan Meranti","Selatpanjang"],
  ["Riau","Kota","Dumai",""],
  ["Riau","Kota","Pekanbaru",""],
  ["Sumatera Barat","Kabupaten","Agam","Lubuk Basung"],
  ["Sumatera Barat","Kabupaten","Dharmasraya","Pulau Punjung"],
  ["Sumatera Barat","Kabupaten","Kepulauan Mentawai","Tuapejat"],
  ["Sumatera Barat","Kabupaten","Lima Puluh Kota","Sarilamak"],
  ["Sumatera Barat","Kabupaten","Padang Pariaman","Parit Malintang"],
  ["Sumatera Barat","Kabupaten","Pasaman","Lubuk Sikaping"],
  ["Sumatera Barat","Kabupaten","Pasaman Barat","Simpang Empat"],
  ["Sumatera Barat","Kabupaten","Pesisir Selatan","Painan"],
  ["Sumatera Barat","Kabupaten","Sijunjung","Muaro Sijunjung"],
  ["Sumatera Barat","Kabupaten","Solok","Arosuka"],
  ["Sumatera Barat","Kabupaten","Solok Selatan","Padang Aro"],
  ["Sumatera Barat","Kabupaten","Tanah Datar","Batusangkar"],
  ["Sumatera Barat","Kota","Bukittinggi","Bukittinggi"],
  ["Sumatera Barat","Kota","Padang","Padang"],
  ["Sumatera Barat","Kota","Padangpanjang","Padangpanjang"],
  ["Sumatera Barat","Kota","Pariaman","Pariaman"],
  ["Sumatera Barat","Kota","Payakumbuh","Payakumbuh"],
  ["Sumatera Barat","Kota","Sawahlunto","Sawahlunto"],
  ["Sumatera Barat","Kota","Solok","Solok"],
  ["Sumatera Selatan","Kabupaten","Banyuasin","Pangkalan Balai"],
  ["Sumatera Selatan","Kabupaten","Empat Lawang","Tebing Tinggi"],
  ["Sumatera Selatan","Kabupaten","Lahat","Lahat"],
  ["Sumatera Selatan","Kabupaten","Muara Enim","Muara Enim"],
  ["Sumatera Selatan","Kabupaten","Musi Banyuasin","Sekayu"],
  ["Sumatera Selatan","Kabupaten","Musi Rawas","Muara Beliti Baru"],
  ["Sumatera Selatan","Kabupaten","Ogan Ilir","Indralaya"],
  ["Sumatera Selatan","Kabupaten","Ogan Komering Ilir","Kota Kayu Agung"],
  ["Sumatera Selatan","Kabupaten","Ogan Komering Ulu","Baturaja"],
  ["Sumatera Selatan","Kabupaten","Ogan Komering Ulu Selatan","Muaradua"],
  ["Sumatera Selatan","Kabupaten","Ogan Komering Ulu Timur","Martapura"],
  ["Sumatera Selatan","Kota","Lubuklinggau",""],
  ["Sumatera Selatan","Kota","Pagar Alam",""],
  ["Sumatera Selatan","Kota","Palembang",""],
  ["Sumatera Selatan","Kota","Prabumulih",""],
  ["Lampung","Kabupaten","Lampung Barat","Kota Liwa"],
  ["Lampung","Kabupaten","Lampung Selatan","Kalianda"],
  ["Lampung","Kabupaten","Lampung Tengah","Gunung Sugih"],
  ["Lampung","Kabupaten","Lampung Timur","Sukadana"],
  ["Lampung","Kabupaten","Lampung Utara","Kotabumi"],
  ["Lampung","Kabupaten","Mesuji",""],
  ["Lampung","Kabupaten","Pesawaran","Gedong Tataan"],
  ["Lampung","Kabupaten","Pringsewu","Pringsewu"],
  ["Lampung","Kabupaten","Tanggamus","Kota Agung"],
  ["Lampung","Kabupaten","Tulang Bawang","Menggala"],
  ["Lampung","Kabupaten","Tulang Bawang Barat","Tulang Bawang Tengah"],
  ["Lampung","Kabupaten","Way Kanan","Blambangan Umpu"],
  ["Lampung","Kota","Bandar Lampung",""],
  ["Lampung","Kota","Metro",""],
  ["Kepulauan Bangka Belitung","Kabupaten","Bangka","Sungai Liat"],
  ["Kepulauan Bangka Belitung","Kabupaten","Bangka Barat","Toboali"],
  ["Kepulauan Bangka Belitung","Kabupaten","Bangka Selatan","Mentok"],
  ["Kepulauan Bangka Belitung","Kabupaten","Bangka Tengah","Koba"],
  ["Kepulauan Bangka Belitung","Kabupaten","Belitung","Tanjung Pandan"],
  ["Kepulauan Bangka Belitung","Kabupaten","Belitung Timur","Manggar"],
  ["Kepulauan Bangka Belitung","Kota","Pangkal Pinang",""],
  ["Kepulauan Riau","Kabupaten","Bintan","Bandar Seri Bentan"],
  ["Kepulauan Riau","Kabupaten","Karimun","Tanjung Balai Karimun"],
  ["Kepulauan Riau","Kabupaten","Kepulauan Anambas","Terempa"],
  ["Kepulauan Riau","Kabupaten","Lingga","Daik,Lingga"],
  ["Kepulauan Riau","Kabupaten","Natuna","Ranai,Bunguran Timur"],
  ["Kepulauan Riau","Kota","Batam",""],
  ["Kepulauan Riau","Kota","Tanjung Pinang",""],
  ["Banten","Kabupaten","Tangerang","Tigaraksa"],
  ["Banten","Kabupaten","Serang","Ciruas"],
  ["Banten","Kabupaten","Lebak","Rangkasbitung"],
  ["Banten","Kabupaten","Pandeglang","Pandeglang"],
  ["Banten","Kota","Tangerang",""],
  ["Banten","Kota","Serang",""],
  ["Banten","Kota","Cilegon",""],
  ["Banten","Kota","Tangerang Selatan","Ciputat"],
  ["Jawa Barat","Kabupaten","Bandung","Soreang"],
  ["Jawa Barat","Kabupaten","Bandung Barat","Ngamprah"],
  ["Jawa Barat","Kabupaten","Bekasi","Cikarang"],
  ["Jawa Barat","Kabupaten","Bogor","Cibinong"],
  ["Jawa Barat","Kabupaten","Ciamis","Ciamis"],
  ["Jawa Barat","Kabupaten","Cianjur","Cianjur"],
  ["Jawa Barat","Kabupaten","Cirebon","Sumber"],
  ["Jawa Barat","Kabupaten","Garut","Garut"],
  ["Jawa Barat","Kabupaten","Indramayu","Indramayu"],
  ["Jawa Barat","Kabupaten","Karawang","Karawang"],
  ["Jawa Barat","Kabupaten","Kuningan","Kuningan"],
  ["Jawa Barat","Kabupaten","Majalengka","Majalengka"],
  ["Jawa Barat","Kabupaten","Purwakarta","Purwakarta"],
  ["Jawa Barat","Kabupaten","Subang","Subang"],
  ["Jawa Barat","Kabupaten","Sukabumi","Pelabuanratu"],
  ["Jawa Barat","Kabupaten","Sumedang","Sumedang"],
  ["Jawa Barat","Kabupaten","Tasikmalaya","Singaparna"],
  ["Jawa Barat","Kota","Bandung","Bandung"],
  ["Jawa Barat","Kota","Banjar","Banjar"],
  ["Jawa Barat","Kota","Bekasi","Bekasi"],
  ["Jawa Barat","Kota","Bogor","Bogor"],
  ["Jawa Barat","Kota","Cimahi","Cimahi"],
  ["Jawa Barat","Kota","Cirebon","Cirebon"],
  ["Jawa Barat","Kota","Depok","Depok"],
  ["Jawa Barat","Kota","Sukabumi","Cisaat"],
  ["Jawa Barat","Kota","Tasikmalaya","Tasikmalaya"],
  ["DKI Jakarta","Kabupaten Administrasi","Kepulauan Seribu","Pulau Pramuka"],
  ["DKI Jakarta","Kota Administrasi","Jakarta Barat",""],
  ["DKI Jakarta","Kota Administrasi","Jakarta Pusat","Menteng"],
  ["DKI Jakarta","Kota Administrasi","Jakarta Selatan",""],
  ["DKI Jakarta","Kota Administrasi","Jakarta Timur","Jatinegara"],
  ["DKI Jakarta","Kota Administrasi","Jakarta Utara","Koja"],
  ["Jawa Tengah","Kabupaten","Banjarnegara","Banjarnegara"],
  ["Jawa Tengah","Kabupaten","Banyumas","Purwokerto"],
  ["Jawa Tengah","Kabupaten","Batang","Batang"],
  ["Jawa Tengah","Kabupaten","Blora","Blora"],
  ["Jawa Tengah","Kabupaten","Boyolali","Boyolali"],
  ["Jawa Tengah","Kabupaten","Brebes","Brebes,Bumiayu"],
  ["Jawa Tengah","Kabupaten","Cilacap","Cilacap"],
  ["Jawa Tengah","Kabupaten","Demak","Demak"],
  ["Jawa Tengah","Kabupaten","Grobogan","Purwodadi"],
  ["Jawa Tengah","Kabupaten","Jepara","Jepara"],
  ["Jawa Tengah","Kabupaten","Karanganyar","Karanganyar"],
  ["Jawa Tengah","Kabupaten","Kebumen","Kebumen"],
  ["Jawa Tengah","Kabupaten","Kendal","Kendal"],
  ["Jawa Tengah","Kabupaten","Klaten","Klaten"],
  ["Jawa Tengah","Kabupaten","Kudus","Kudus"],
  ["Jawa Tengah","Kabupaten","Magelang","Kota Mungkid"],
  ["Jawa Tengah","Kabupaten","Pati","Pati"],
  ["Jawa Tengah","Kabupaten","Pekalongan","Kajen"],
  ["Jawa Tengah","Kabupaten","Pemalang","Pemalang"],
  ["Jawa Tengah","Kabupaten","Purbalingga","Purbalingga"],
  ["Jawa Tengah","Kabupaten","Purworejo","Purworejo"],
  ["Jawa Tengah","Kabupaten","Rembang","Rembang"],
  ["Jawa Tengah","Kabupaten","Semarang","Ungaran"],
  ["Jawa Tengah","Kabupaten","Sragen","Sragen"],
  ["Jawa Tengah","Kabupaten","Sukoharjo","Sukoharjo"],
  ["Jawa Tengah","Kabupaten","Tegal","Slawi"],
  ["Jawa Tengah","Kabupaten","Temanggung","Temanggung"],
  ["Jawa Tengah","Kabupaten","Wonogiri","Wonogiri"],
  ["Jawa Tengah","Kabupaten","Wonosobo","Wonosobo"],
  ["Jawa Tengah","Kota","Magelang",""],
  ["Jawa Tengah","Kota","Pekalongan",""],
  ["Jawa Tengah","Kota","Salatiga",""],
  ["Jawa Tengah","Kota","Semarang",""],
  ["Jawa Tengah","Kota","Surakarta",""],
  ["Jawa Tengah","Kota","Tegal",""],
  ["Jawa Timur","Kabupaten","Bangkalan","Bangkalan"],
  ["Jawa Timur","Kabupaten","Banyuwangi","Banyuwangi"],
  ["Jawa Timur","Kabupaten","Blitar","Kanigoro"],
  ["Jawa Timur","Kabupaten","Bojonegoro","Bojonegoro"],
  ["Jawa Timur","Kabupaten","Bondowoso","Bondowoso"],
  ["Jawa Timur","Kabupaten","Gresik","Gresik"],
  ["Jawa Timur","Kabupaten","Jember","Jember"],
  ["Jawa Timur","Kabupaten","Jombang","Jombang"],
  ["Jawa Timur","Kabupaten","Kediri","Kediri"],
  ["Jawa Timur","Kabupaten","Lamongan","Lamongan"],
  ["Jawa Timur","Kabupaten","Lumajang","Lumajang"],
  ["Jawa Timur","Kabupaten","Madiun","Madiun"],
  ["Jawa Timur","Kabupaten","Magetan","Magetan"],
  ["Jawa Timur","Kabupaten","Malang","Kepanjen"],
  ["Jawa Timur","Kabupaten","Mojokerto","Mojokerto"],
  ["Jawa Timur","Kabupaten","Nganjuk","Nganjuk"],
  ["Jawa Timur","Kabupaten","Ngawi","Ngawi"],
  ["Jawa Timur","Kabupaten","Pacitan","Pacitan"],
  ["Jawa Timur","Kabupaten","Pamekasan","Pamekasan"],
  ["Jawa Timur","Kabupaten","Pasuruan","Pasuruan"],
  ["Jawa Timur","Kabupaten","Ponorogo","Ponorogo"],
  ["Jawa Timur","Kabupaten","Probolinggo","Kraksaan"],
  ["Jawa Timur","Kabupaten","Sampang","Sampang"],
  ["Jawa Timur","Kabupaten","Sidoarjo","Sidoarjo"],
  ["Jawa Timur","Kabupaten","Situbondo","Situbondo"],
  ["Jawa Timur","Kabupaten","Sumenep","Sumenep"],
  ["Jawa Timur","Kabupaten","Trenggalek","Trenggalek"],
  ["Jawa Timur","Kabupaten","Tuban","Tuban"],
  ["Jawa Timur","Kabupaten","Tulungagung","Tulungagung"],
  ["Jawa Timur","Kota","Batu",""],
  ["Jawa Timur","Kota","Blitar",""],
  ["Jawa Timur","Kota","Kediri",""],
  ["Jawa Timur","Kota","Madiun",""],
  ["Jawa Timur","Kota","Malang",""],
  ["Jawa Timur","Kota","Mojokerto",""],
  ["Jawa Timur","Kota","Pasuruan",""],
  ["Jawa Timur","Kota","Probolinggo",""],
  ["Jawa Timur","Kota","Surabaya",""],
  ["Daerah Istimewa Yogyakarta","Kabupaten","Bantul","Kecamatan Bantul"],
  ["Daerah Istimewa Yogyakarta","Kabupaten","Gunung Kidul","Kecamatan Wonosari"],
  ["Daerah Istimewa Yogyakarta","Kabupaten","Kulon Progo","Kecamatan Wates"],
  ["Daerah Istimewa Yogyakarta","Kabupaten","Sleman","Kecamatan Sleman"],
  ["Daerah Istimewa Yogyakarta","Kota","Yogyakarta","Kecamatan Umbulharjo"],
  ["Bali","Kabupaten","Badung","Badung"],
  ["Bali","Kabupaten","Bangli","Bangli"],
  ["Bali","Kabupaten","Buleleng","Singaraja"],
  ["Bali","Kabupaten","Gianyar","Gianyar"],
  ["Bali","Kabupaten","Jembrana","Negara"],
  ["Bali","Kabupaten","Karangasem","Karangasem"],
  ["Bali","Kabupaten","Klungkung","Klungkung"],
  ["Bali","Kabupaten","Tabanan","Tabanan"],
  ["Bali","Kota","Denpasar",""],
  ["Nusa Tenggara Barat","Kabupaten","Bima","Raba"],
  ["Nusa Tenggara Barat","Kabupaten","Dompu","Dompu"],
  ["Nusa Tenggara Barat","Kabupaten","Lombok Barat","Mataram"],
  ["Nusa Tenggara Barat","Kabupaten","Lombok Tengah","Praya"],
  ["Nusa Tenggara Barat","Kabupaten","Lombok Timur","Selong"],
  ["Nusa Tenggara Barat","Kabupaten","Lombok Utara","Tanjung"],
  ["Nusa Tenggara Barat","Kabupaten","Sumbawa","Sumbawa Besar"],
  ["Nusa Tenggara Barat","Kabupaten","Sumbawa Barat","Taliwang"],
  ["Nusa Tenggara Barat","Kota","Bima",""],
  ["Nusa Tenggara Barat","Kota","Mataram",""],
  ["Nusa Tenggara Timur","Kabupaten","Alor","Kalabahi"],
  ["Nusa Tenggara Timur","Kabupaten","Belu","Atambua"],
  ["Nusa Tenggara Timur","Kabupaten","Ende","Ende"],
  ["Nusa Tenggara Timur","Kabupaten","Flores Timur","Larantuka"],
  ["Nusa Tenggara Timur","Kabupaten","Kupang","Kupang"],
  ["Nusa Tenggara Timur","Kabupaten","Lembata","Lewoleba"],
  ["Nusa Tenggara Timur","Kabupaten","Manggarai","Ruteng"],
  ["Nusa Tenggara Timur","Kabupaten","Manggarai Barat","Labuan Bajo"],
  ["Nusa Tenggara Timur","Kabupaten","Manggarai Timur","Borong"],
  ["Nusa Tenggara Timur","Kabupaten","Ngada","Bajawa"],
  ["Nusa Tenggara Timur","Kabupaten","Nagekeo","Mbay"],
  ["Nusa Tenggara Timur","Kabupaten","Rote Ndao","Baa"],
  ["Nusa Tenggara Timur","Kabupaten","Sabu Raijua","Seba"],
  ["Nusa Tenggara Timur","Kabupaten","Sikka","Maumere"],
  ["Nusa Tenggara Timur","Kabupaten","Sumba Barat","Waikabubak"],
  ["Nusa Tenggara Timur","Kabupaten","Sumba Barat Daya","Tambolaka"],
  ["Nusa Tenggara Timur","Kabupaten","Sumba Tengah","Waibakul"],
  ["Nusa Tenggara Timur","Kabupaten","Sumba Timur","Waingapu"],
  ["Nusa Tenggara Timur","Kabupaten","Timor Tengah Selatan","Soe"],
  ["Nusa Tenggara Timur","Kabupaten","Timor Tengah Utara","Kefamenanu"],
  ["Nusa Tenggara Timur","Kota","Kupang","Kupang"],
  ["Kalimantan Barat","Kabupaten","Bengkayang","Bengkayang"],
  ["Kalimantan Barat","Kabupaten","Kapuas Hulu","Putussibau"],
  ["Kalimantan Barat","Kabupaten","Kayong Utara","Sukadana"],
  ["Kalimantan Barat","Kabupaten","Ketapang","Ketapang"],
  ["Kalimantan Barat","Kabupaten","Kubu Raya","Sungai Raya"],
  ["Kalimantan Barat","Kabupaten","Landak","Ngabang"],
  ["Kalimantan Barat","Kabupaten","Melawi","Nanga Pinoh"],
  ["Kalimantan Barat","Kabupaten","Pontianak","Mempawah"],
  ["Kalimantan Barat","Kabupaten","Sambas","Sambas"],
  ["Kalimantan Barat","Kabupaten","Sanggau","Sanggau"],
  ["Kalimantan Barat","Kabupaten","Sekadau","Sekadau"],
  ["Kalimantan Barat","Kabupaten","Sintang","Sintang"],
  ["Kalimantan Barat","Kota","Pontianak",""],
  ["Kalimantan Barat","Kota","Singkawang",""],
  ["Kalimantan Selatan","Kabupaten","Balangan","Paringin"],
  ["Kalimantan Selatan","Kabupaten","Banjar","Martapura"],
  ["Kalimantan Selatan","Kabupaten","Barito Kuala","Marabahan"],
  ["Kalimantan Selatan","Kabupaten","Hulu Sungai Selatan","Kandangan"],
  ["Kalimantan Selatan","Kabupaten","Hulu Sungai Tengah","Barabai"],
  ["Kalimantan Selatan","Kabupaten","Hulu Sungai Utara","Amuntai"],
  ["Kalimantan Selatan","Kabupaten","Kotabaru","Kotabaru"],
  ["Kalimantan Selatan","Kabupaten","Tabalong","Tanjung"],
  ["Kalimantan Selatan","Kabupaten","Tanah Bumbu","Batulicin"],
  ["Kalimantan Selatan","Kabupaten","Tanah Laut","Pelaihari"],
  ["Kalimantan Selatan","Kabupaten","Tapin","Rantau"],
  ["Kalimantan Selatan","Kota","Banjarbaru","Banjarbaru Kota"],
  ["Kalimantan Selatan","Kota","Banjarmasin","Banjarmasin"],
  ["Kalimantan Tengah","Kabupaten","Barito Selatan","Buntok"],
  ["Kalimantan Tengah","Kabupaten","Barito Timur","Tamiang"],
  ["Kalimantan Tengah","Kabupaten","Barito Utara","Muara Teweh"],
  ["Kalimantan Tengah","Kabupaten","Gunung Mas","Kuala Kurun"],
  ["Kalimantan Tengah","Kabupaten","Kapuas","Kuala Kapuas"],
  ["Kalimantan Tengah","Kabupaten","Katingan","Kasongan"],
  ["Kalimantan Tengah","Kabupaten","Kotawaringin Barat","Pangkalan Bun"],
  ["Kalimantan Tengah","Kabupaten","Kotawaringin Timur","Sampit"],
  ["Kalimantan Tengah","Kabupaten","Lamandau","Nanga Bulik"],
  ["Kalimantan Tengah","Kabupaten","Murung Raya","Purukcahu"],
  ["Kalimantan Tengah","Kabupaten","Pulang Pisau","Pulang Pisau"],
  ["Kalimantan Tengah","Kabupaten","Sukamara","Sukamara"],
  ["Kalimantan Tengah","Kabupaten","Seruyan","Kuala Pembuang"],
  ["Kalimantan Tengah","Kota","Palangka Raya",""],
  ["Kalimantan Timur","Kabupaten","Berau","Tanjungredep"],
  ["Kalimantan Timur","Kabupaten","Bulungan","Tanjungselor"],
  ["Kalimantan Timur","Kabupaten","Kutai Barat","Sendawar"],
  ["Kalimantan Timur","Kabupaten","Kutai Kartanegara","Tenggarong"],
  ["Kalimantan Timur","Kabupaten","Kutai Timur","Sangatta"],
  ["Kalimantan Timur","Kabupaten","Malinau","Malinau"],
  ["Kalimantan Timur","Kabupaten","Nunukan","Nunukan"],
  ["Kalimantan Timur","Kabupaten","Paser","Tanah Grogot"],
  ["Kalimantan Timur","Kabupaten","Penajam Paser Utara","Penajam"],
  ["Kalimantan Timur","Kabupaten","Tana Tidung","Tideng Pale"],
  ["Kalimantan Timur","Kota","Balikpapan",""],
  ["Kalimantan Timur","Kota","Bontang",""],
  ["Kalimantan Timur","Kota","Samarinda",""],
  ["Kalimantan Timur","Kota","Tarakan",""],
  ["Gorontalo","Kabupaten","Boalemo","Tilamuta"],
  ["Gorontalo","Kabupaten","Bone Bolango","Suwawa"],
  ["Gorontalo","Kabupaten","Gorontalo","Gorontalo"],
  ["Gorontalo","Kabupaten","Gorontalo Utara","Kwandang"],
  ["Gorontalo","Kabupaten","Pohuwato","Marisa"],
  ["Gorontalo","Kota","Gorontalo",""],
  ["Sulawesi Selatan","Kabupaten","Bantaeng","Bantaeng"],
  ["Sulawesi Selatan","Kabupaten","Barru","Barru"],
  ["Sulawesi Selatan","Kabupaten","Bone","Watampone"],
  ["Sulawesi Selatan","Kabupaten","Bulukumba","Bulukumba"],
  ["Sulawesi Selatan","Kabupaten","Enrekang","Enrekang"],
  ["Sulawesi Selatan","Kabupaten","Gowa","Sungguminasa"],
  ["Sulawesi Selatan","Kabupaten","Jeneponto","Jeneponto"],
  ["Sulawesi Selatan","Kabupaten","Kepulauan Selayar","Benteng"],
  ["Sulawesi Selatan","Kabupaten","Luwu","Belopa"],
  ["Sulawesi Selatan","Kabupaten","Luwu Timur","Malili"],
  ["Sulawesi Selatan","Kabupaten","Luwu Utara","Masamba"],
  ["Sulawesi Selatan","Kabupaten","Maros","Turikale"],
  ["Sulawesi Selatan","Kabupaten","Pangkajene dan Kepulauan","Pangkajene"],
  ["Sulawesi Selatan","Kabupaten","Pinrang","Pinrang"],
  ["Sulawesi Selatan","Kabupaten","Sidenreng Rappang","Pangkajene Sidenreng"],
  ["Sulawesi Selatan","Kabupaten","Sinjai","Sinjai"],
  ["Sulawesi Selatan","Kabupaten","Soppeng","Watan Soppeng"],
  ["Sulawesi Selatan","Kabupaten","Takalar","Pattalassang"],
  ["Sulawesi Selatan","Kabupaten","Tana Toraja","Makale"],
  ["Sulawesi Selatan","Kabupaten","Toraja Utara","Rantepao"],
  ["Sulawesi Selatan","Kabupaten","Wajo","Sengkang"],
  ["Sulawesi Selatan","Kota","Makassar",""],
  ["Sulawesi Selatan","Kota","Palopo",""],
  ["Sulawesi Selatan","Kota","Parepare",""],
  ["Sulawesi Tenggara","Kabupaten","Bombana","Rumbia"],
  ["Sulawesi Tenggara","Kabupaten","Buton","Pasarwajo"],
  ["Sulawesi Tenggara","Kabupaten","Buton Utara","Buranga"],
  ["Sulawesi Tenggara","Kabupaten","Kolaka","Kolaka"],
  ["Sulawesi Tenggara","Kabupaten","Kolaka Utara","Lasusua"],
  ["Sulawesi Tenggara","Kabupaten","Konawe","Unaaha"],
  ["Sulawesi Tenggara","Kabupaten","Konawe Selatan","Andolo"],
  ["Sulawesi Tenggara","Kabupaten","Konawe Utara","Wanggudu"],
  ["Sulawesi Tenggara","Kabupaten","Muna","Raha"],
  ["Sulawesi Tenggara","Kabupaten","Wakatobi","Wangi-Wangi"],
  ["Sulawesi Tenggara","Kota","Bau-Bau",""],
  ["Sulawesi Tenggara","Kota","Kendari",""],
  ["Sulawesi Tengah","Kabupaten","Banggai","Luwuk"],
  ["Sulawesi Tengah","Kabupaten","Banggai Kepulauan","Banggai"],
  ["Sulawesi Tengah","Kabupaten","Buol","Buol"],
  ["Sulawesi Tengah","Kabupaten","Donggala","Donggala"],
  ["Sulawesi Tengah","Kabupaten","Morowali","Bungku"],
  ["Sulawesi Tengah","Kabupaten","Parigi Moutong","Parigi"],
  ["Sulawesi Tengah","Kabupaten","Poso","Poso"],
  ["Sulawesi Tengah","Kabupaten","Tojo Una-Una","Ampana"],
  ["Sulawesi Tengah","Kabupaten","Toli-Toli","Toli-Toli"],
  ["Sulawesi Tengah","Kabupaten","Sigi","Sigi Biromaru"],
  ["Sulawesi Tengah","Kota","Palu",""],
  ["Sulawesi Utara","Kabupaten","Bolaang Mongondow","Kotamobagu"],
  ["Sulawesi Utara","Kabupaten","Bolaang Mongondow Selatan","Bolaang Uki"],
  ["Sulawesi Utara","Kabupaten","Bolaang Mongondow Timur","Tutuyan"],
  ["Sulawesi Utara","Kabupaten","Bolaang Mongondow Utara","Boroko"],
  ["Sulawesi Utara","Kabupaten","Kepulauan Sangihe","Tahuna"],
  ["Sulawesi Utara","Kabupaten","Kepulauan Siau Tagulandang Biaro","Ondong Siau"],
  ["Sulawesi Utara","Kabupaten","Kepulauan Talaud","Melonguane"],
  ["Sulawesi Utara","Kabupaten","Minahasa","Tondano"],
  ["Sulawesi Utara","Kabupaten","Minahasa Selatan","Amurang"],
  ["Sulawesi Utara","Kabupaten","Minahasa Tenggara","Ratahan"],
  ["Sulawesi Utara","Kabupaten","Minahasa Utara","Airmadidi"],
  ["Sulawesi Utara","Kota","Bitung",""],
  ["Sulawesi Utara","Kota","Kotamobagu",""],
  ["Sulawesi Utara","Kota","Manado",""],
  ["Sulawesi Utara","Kota","Tomohon",""],
  ["Sulawesi Barat","Kabupaten","Majene","Majene"],
  ["Sulawesi Barat","Kabupaten","Mamasa","Mamasa"],
  ["Sulawesi Barat","Kabupaten","Mamuju","Mamuju"],
  ["Sulawesi Barat","Kabupaten","Mamuju Utara","Pasangkayu"],
  ["Sulawesi Barat","Kabupaten","Polewali Mandar","Polewali"],
  ["Maluku","Kabupaten","Buru","Namlea"],
  ["Maluku","Kabupaten","Buru Selatan","Namrole"],
  ["Maluku","Kabupaten","Kepulauan Aru","Dobo"],
  ["Maluku","Kabupaten","Maluku Barat Daya","Wonreli"],
  ["Maluku","Kabupaten","Maluku Tengah","Masohi"],
  ["Maluku","Kabupaten","Maluku Tenggara","Langgur"],
  ["Maluku","Kabupaten","Maluku Tenggara Barat","Saumlaki"],
  ["Maluku","Kabupaten","Seram Bagian Barat","Piru"],
  ["Maluku","Kabupaten","Seram Bagian Timur","Bula"],
  ["Maluku","Kota","Ambon",""],
  ["Maluku","Kota","Tual",""],
  ["Maluku Utara","Kabupaten","Halmahera Barat","Jailolo"],
  ["Maluku Utara","Kabupaten","Halmahera Tengah","Weda"],
  ["Maluku Utara","Kabupaten","Halmahera Utara","Tobelo"],
  ["Maluku Utara","Kabupaten","Halmahera Selatan","Labuha"],
  ["Maluku Utara","Kabupaten","Kepulauan Sula","Sanana"],
  ["Maluku Utara","Kabupaten","Halmahera Timur","Maba"],
  ["Maluku Utara","Kabupaten","Pulau Morotai","Morotai Selatan"],
  ["Maluku Utara","Kota","Ternate","Ternate"],
  ["Maluku Utara","Kota","Tidore Kepulauan","Soasiu"],
  ["Papua","Kabupaten","Asmat","Agats"],
  ["Papua","Kabupaten","Biak Numfor","Biak"],
  ["Papua","Kabupaten","Boven Digoel","Tanah Merah"],
  ["Papua","Kabupaten","Deiyai","Tigi"],
  ["Papua","Kabupaten","Dogiyai","Kigamani"],
  ["Papua","Kabupaten","Intan Jaya","Sugapa"],
  ["Papua","Kabupaten","Jayapura","Sentani"],
  ["Papua","Kabupaten","Jayawijaya","Wamena"],
  ["Papua","Kabupaten","Keerom","Waris"],
  ["Papua","Kabupaten","Kepulauan Yapen","Serui"],
  ["Papua","Kabupaten","Lanny Jaya","Tiom"],
  ["Papua","Kabupaten","Mamberamo Raya","Burmeso"],
  ["Papua","Kabupaten","Mamberamo Tengah","Kobakma"],
  ["Papua","Kabupaten","Mappi","Kepi"],
  ["Papua","Kabupaten","Merauke","Merauke"],
  ["Papua","Kabupaten","Mimika","Timika"],
  ["Papua","Kabupaten","Nabire","Nabire"],
  ["Papua","Kabupaten","Nduga","Kenyam"],
  ["Papua","Kabupaten","Paniai","Enarotali"],
  ["Papua","Kabupaten","Pegunungan Bintang","Oksibil"],
  ["Papua","Kabupaten","Puncak","Ilaga"],
  ["Papua","Kabupaten","Puncak Jaya","Kotamulia"],
  ["Papua","Kabupaten","Sarmi","Sarmi"],
  ["Papua","Kabupaten","Supiori","Sorendiweri"],
  ["Papua","Kabupaten","Tolikara","Karubaga"],
  ["Papua","Kabupaten","Waropen","Botawa"],
  ["Papua","Kabupaten","Yahukimo","Sumohai"],
  ["Papua","Kabupaten","Yalimo","Elelim"],
  ["Papua","Kota","Jayapura",""],
  ["Papua Barat","Kabupaten","Fakfak","Fakfak"],
  ["Papua Barat","Kabupaten","Kaimana","Kaimana"],
  ["Papua Barat","Kabupaten","Manokwari","Manokwari"],
  ["Papua Barat","Kabupaten","Maybrat","Kumurkek"],
  ["Papua Barat","Kabupaten","Raja Ampat","Waisai"],
  ["Papua Barat","Kabupaten","Sorong","Sorong"],
  ["Papua Barat","Kabupaten","Sorong Selatan","Teminabuan"],
  ["Papua Barat","Kabupaten","Tambrauw","Fef"],
  ["Papua Barat","Kabupaten","Teluk Bintuni","Bintuni"],
  ["Papua Barat","Kabupaten","Teluk Wondama","Rasiei"],
  ["Papua Barat","Kota","Sorong",""]
]

kabupatens.each do |item|
  Kabupaten.create(
    province: Province.find_or_create_by_name(item[0]),
    category: Dt2Category.find_or_create_by_name(item[1]),  
    name:     item[2],
    capital:  item[3]
  )
end
